apiVersion: batch/v1
kind: Job
metadata:
  name: tandem-batch-job-rerun-2
spec:
  backoffLimit: 3
  completionMode: Indexed
  completions: 6
  parallelism: 6
  template:
    metadata:
      labels:
        app: tandem-job
    spec:
      containers:
      - command:
        - bash
        - -c
        - items=('77.5 5.0' '72.5 3.0' '100.0 6.0' '68.125 2.0' '65.0 3.0' '70.0 5.0');cd
          /home/tandem/storage/;python3 run_sim.py ${items[${JOB_COMPLETION_INDEX}]}
          /home/tandem/storage/ /home/tandem/storage/gf/ /home/tandem/casc/casc.msh
          /home/tandem/casc/casc.lua /home/tandem/build_2d_6p/app/tandem /home/tandem/casc/solver.cfg
        env:
        - name: OPENMPI_ALLOW_RUN_AS_ROOT
          value: '1'
        - name: OMP_PROC_BIND
          value: 'true'
        - name: OMP_PLACES
          value: cores
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        image: yohaimagen1/tandem_v1.2:latest
        imagePullPolicy: Always
        name: tandem-container
        resources:
          limits:
            cpu: '50'
            memory: 80Gi
          requests:
            cpu: '30'
            memory: 80Gi
        volumeMounts:
        - mountPath: /home/tandem/storage
          name: yohai-magen-sse-pvc
      restartPolicy: Never
      volumes:
      - name: yohai-magen-sse-pvc
        persistentVolumeClaim:
          claimName: yohai-magen-sse-pvc
