apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yohai-magen-sse-pvc
spec:
  storageClassName:  rook-cephfs #rook-ceph-block  
  accessModes:
    -  ReadWriteMany   #ReadWriteOnce
  resources:
    requests:
      storage: 300Gi

