apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yohai-magen-sse-pvc
spec:
  storageClassName: rook-ceph-block  
  accessModes:
    - ReadWriteOnce #ReadWriteMany  
  resources:
    requests:
      storage: 100Gi  

