apiVersion: apps/v1
kind: Deployment
metadata:
  name: tandem-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tandem-pod
  template:
    metadata:
      labels:
        app: tandem-pod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - "true"
      containers:
      - name: tandem-pod
        image: yohaimagen1/tandem_v1.2:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /home/tandem/storage
            name: yohai-magen-sse-pvc
        resources:
          limits:
            memory: 80Gi
            cpu: "50"
          requests:
            memory: 80Gi
            cpu: "30"
        command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
        env:
        - name: OPENMPI_ALLOW_RUN_AS_ROOT
          value: "1"
        - name: OMP_PROC_BIND
          value: "true"
        - name: OMP_PLACES
          value: "cores"
      volumes:
      - name: yohai-magen-sse-pvc
        persistentVolumeClaim:
          claimName: yohai-magen-sse-pvc
