apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-pod
  template:
    metadata:
      labels:
        app: debug-pod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - "true"
      containers:
      - name: tandem-pod
        image: quay.io/jupyter/scipy-notebook
        volumeMounts:
          - mountPath: /home/jovyan/work
            name: yohai-magen-sse-pvc
        resources:
          limits:
            memory: 80Gi
            cpu: "30"
          requests:
            memory: 80Gi
            cpu: "20"
        command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
        env:
        - name: OPENMPI_ALLOW_RUN_AS_ROOT
          value: "1"
        - name: OMP_PROC_BIND
          value: "true"
        - name: OMP_PLACES
          value: "cores"
      volumes:
      - name: yohai-magen-sse-pvc
        persistentVolumeClaim:
          claimName: yohai-magen-sse-pvc
